version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sweaterdb
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --encoding=UTF-8 --locale=ru_RU.UTF-8
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data
      TZ: Europe/Minsk
      LANG: ru_RU.UTF-8
      LANGUAGE: ru
    restart: always
  pgadmin:
    image: dpage/pgadmin4:6.2
    container_name: pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Europe/Minsk
      LANG: ru_RU.UTF-8
      LANGUAGE: ru
    restart: always
    depends_on:
      - postgres
  sweater:
    build: .
    container_name: sweater
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./logs:/usr/local/tomcat/logs
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: sweaterdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: prod
      CATALINA_OPTS: -Xms512m -Xmx2048m -XX:MaxPermSize=256m -server
      TZ: Europe/Minsk
      LANG: ru_RU.UTF-8
      LANGUAGE: ru
    restart: always
    depends_on:
      - postgres
volumes:
  pg_data: {}
